-- V10__expanded_official_sources.sql
-- 扩展官方源注册表：国际高价值网络安全法规/认证来源

INSERT INTO official_sources
    (country_code, name, base_url, list_url, source_type, allowed_domains, entry_type_scope, priority, parser_config)
VALUES
    (
        'AU',
        'Cyber.gov.au Secure by Design',
        'https://www.cyber.gov.au',
        'https://www.cyber.gov.au/business-government/secure-design/secure-by-design/iot-secure-by-design-guidance-for-manufacturers',
        'html_list',
        ARRAY['cyber.gov.au'],
        ARRAY['regulation','standard'],
        8,
        '{
          "url_patterns":[
            "iot-secure-by-design",
            "security-standards-for-smart-devices",
            "smart devices",
            "sites/default/files/.+\\\\.pdf"
          ],
          "exclude_url_patterns":[
            "/search",
            "/contact",
            "/jobs"
          ]
        }'::jsonb
    ),
    (
        'CA',
        'Canada.ca CPCSC',
        'https://www.canada.ca',
        'https://www.canada.ca/en/public-services-procurement/services/industrial-security/security-requirements-contracting/cyber-security-certification-defence-suppliers-canada.html',
        'html_list',
        ARRAY['canada.ca','cyber.gc.ca','canadabuys.canada.ca'],
        ARRAY['certification','standard'],
        9,
        '{
          "url_patterns":[
            "cyber-security-certification-defence-suppliers-canada",
            "cyber-security-certification-level1",
            "meet-level1-certification-requirements",
            "canadian-program-for-cyber-security-certification",
            "ITSP.10.171"
          ],
          "exclude_url_patterns":[
            "evaluation-report",
            "standing-committee",
            "/jobs"
          ]
        }'::jsonb
    ),
    (
        'KR',
        'KISA IoT Security Certification',
        'https://www.kisa.or.kr',
        'https://www.kisa.or.kr/1050608',
        'html_list',
        ARRAY['kisa.or.kr'],
        ARRAY['certification','standard'],
        10,
        '{
          "url_patterns":[
            "보안인증",
            "IoT",
            "인증현황",
            "postSeq=2353"
          ],
          "exclude_url_patterns":[
            "search\\\\.jsp",
            "/403/",
            "\\\\.xlsx$"
          ]
        }'::jsonb
    ),
    (
        'TW',
        'NCC Cybersecurity Equipment Review',
        'https://ncclaw.ncc.gov.tw',
        'https://ncclaw.ncc.gov.tw/FLAW/FLAWDAT0202.aspx?id=FL076356',
        'html_list',
        ARRAY['ncclaw.ncc.gov.tw','ncc.gov.tw'],
        ARRAY['regulation','certification','standard'],
        11,
        '{
          "url_patterns":[
            "FL076356",
            "FL095880",
            "show_file\\\\.aspx",
            "關鍵電信基礎設施",
            "資通設備資通安全"
          ],
          "exclude_url_patterns":[
            "PrintFLAW",
            "reFormatFLAW"
          ]
        }'::jsonb
    ),
    (
        'TW',
        'MODA Communications Cyber Resilience',
        'https://moda.gov.tw',
        'https://moda.gov.tw/digital-affairs/communications-cyber-resilience/operations/328',
        'html_list',
        ARRAY['moda.gov.tw','ncc.gov.tw'],
        ARRAY['regulation','standard'],
        12,
        '{
          "url_patterns":[
            "資通設備安全法規",
            "關鍵電信基礎設施",
            "檢測技術規範",
            "show_file\\\\.aspx"
          ]
        }'::jsonb
    ),
    (
        'CN',
        'MIIT IoT Standards 2024',
        'https://www.miit.gov.cn',
        'https://www.miit.gov.cn/zwgk/zcwj/wjfb/tz/art/2024/art_4ff2646910384278a75238457893a14c.html',
        'html_list',
        ARRAY['miit.gov.cn','gov.cn'],
        ARRAY['regulation','standard'],
        13,
        '{
          "url_patterns":[
            "物联网标准体系建设指南",
            "标准体系建设指南（2024版）",
            "P020240827517418983244\\\\.pdf"
          ]
        }'::jsonb
    ),
    (
        'CN',
        'CAC Laws',
        'https://www.cac.gov.cn',
        'https://www.cac.gov.cn/wxzw/zcfg/fl/A09370301index_1.htm',
        'html_list',
        ARRAY['cac.gov.cn'],
        ARRAY['regulation'],
        14,
        '{
          "url_patterns":[
            "网络安全法",
            "网络安全审查办法",
            "互联网政务应用安全管理规定"
          ],
          "exclude_url_patterns":[
            "专家解读"
          ]
        }'::jsonb
    )
ON CONFLICT (country_code, name) DO NOTHING;
