from __future__ import annotations

from typing import TypedDict


class CountryCatalogItem(TypedDict):
    code: str
    name_zh: str
    name_en: str
    region: str
    priority: str
    jurisdiction_type: str


AFRICA = {
    "AO",
    "BF",
    "BI",
    "BJ",
    "BW",
    "CD",
    "CF",
    "CG",
    "CI",
    "CM",
    "CV",
    "DJ",
    "DZ",
    "EG",
    "ER",
    "ET",
    "GA",
    "GH",
    "GM",
    "GN",
    "GQ",
    "GW",
    "KE",
    "KM",
    "LR",
    "LS",
    "LY",
    "MA",
    "MG",
    "ML",
    "MR",
    "MU",
    "MW",
    "MZ",
    "NA",
    "NE",
    "NG",
    "RW",
    "SC",
    "SD",
    "SL",
    "SN",
    "SO",
    "SS",
    "ST",
    "SZ",
    "TD",
    "TG",
    "TN",
    "TZ",
    "UG",
    "ZA",
    "ZM",
    "ZW",
}

AMERICAS = {
    "AG",
    "AR",
    "BB",
    "BS",
    "BZ",
    "BO",
    "BR",
    "CA",
    "CL",
    "CO",
    "CR",
    "CU",
    "DM",
    "DO",
    "EC",
    "GD",
    "GT",
    "GY",
    "HN",
    "HT",
    "JM",
    "KN",
    "LC",
    "MX",
    "NI",
    "PA",
    "PE",
    "PY",
    "SR",
    "SV",
    "TT",
    "US",
    "UY",
    "VC",
    "VE",
}

EUROPE = {
    "AD",
    "AL",
    "AT",
    "BA",
    "BE",
    "BG",
    "BY",
    "CH",
    "CY",
    "CZ",
    "DE",
    "DK",
    "EE",
    "ES",
    "EU",
    "FI",
    "FR",
    "GB",
    "GR",
    "HR",
    "HU",
    "IE",
    "IS",
    "IT",
    "LI",
    "LT",
    "LU",
    "LV",
    "MC",
    "MD",
    "ME",
    "MK",
    "MT",
    "NL",
    "NO",
    "PL",
    "PT",
    "RO",
    "RS",
    "RU",
    "SE",
    "SI",
    "SK",
    "SM",
    "UA",
    "VA",
    "XK",
}

MIDDLE_EAST = {
    "AE",
    "BH",
    "IL",
    "IQ",
    "IR",
    "JO",
    "KW",
    "LB",
    "OM",
    "PS",
    "QA",
    "SA",
    "SY",
    "TR",
    "YE",
}

CENTRAL_ASIA = {"KG", "KZ", "TJ", "TM", "UZ"}
CAUCASUS = {"AM", "AZ", "GE"}
SOUTH_ASIA = {"AF", "BD", "BT", "IN", "LK", "MV", "NP", "PK"}
EAST_ASIA = {"CN", "HK", "JP", "KP", "KR", "MN", "TW"}
SOUTHEAST_ASIA = {"BN", "ID", "KH", "LA", "MM", "MY", "PH", "SG", "TH", "TL", "VN"}
OCEANIA = {"AU", "FJ", "FM", "KI", "MH", "NR", "NZ", "PG", "PW", "SB", "TO", "TV", "VU", "WS"}


PRIORITY_BY_CODE = {
    "EU": "P1",
    "US": "P1",
    "GB": "P1",
    "CN": "P1",
    "JP": "P1",
    "KR": "P1",
    "SG": "P2",
    "AU": "P2",
    "CA": "P2",
    "IN": "P2",
    "AE": "P2",
    "SA": "P2",
    "MY": "P2",
    "TH": "P2",
    "ID": "P2",
    "VN": "P2",
    "BR": "P2",
    "MX": "P2",
    "TR": "P2",
    "IL": "P2",
}


COUNTRY_ROWS = [
    ("AD", "安道尔", "Andorra"),
    ("AE", "阿联酋", "United Arab Emirates"),
    ("AF", "阿富汗", "Afghanistan"),
    ("AG", "安提瓜和巴布达", "Antigua and Barbuda"),
    ("AL", "阿尔巴尼亚", "Albania"),
    ("AM", "亚美尼亚", "Armenia"),
    ("AO", "安哥拉", "Angola"),
    ("AR", "阿根廷", "Argentina"),
    ("AT", "奥地利", "Austria"),
    ("AU", "澳大利亚", "Australia"),
    ("AZ", "阿塞拜疆", "Azerbaijan"),
    ("BA", "波黑", "Bosnia and Herzegovina"),
    ("BB", "巴巴多斯", "Barbados"),
    ("BD", "孟加拉国", "Bangladesh"),
    ("BE", "比利时", "Belgium"),
    ("BF", "布基纳法索", "Burkina Faso"),
    ("BG", "保加利亚", "Bulgaria"),
    ("BH", "巴林", "Bahrain"),
    ("BI", "布隆迪", "Burundi"),
    ("BJ", "贝宁", "Benin"),
    ("BN", "文莱", "Brunei Darussalam"),
    ("BO", "玻利维亚", "Bolivia"),
    ("BR", "巴西", "Brazil"),
    ("BS", "巴哈马", "Bahamas"),
    ("BT", "不丹", "Bhutan"),
    ("BW", "博茨瓦纳", "Botswana"),
    ("BY", "白俄罗斯", "Belarus"),
    ("BZ", "伯利兹", "Belize"),
    ("CA", "加拿大", "Canada"),
    ("CD", "刚果（金）", "Democratic Republic of the Congo"),
    ("CF", "中非", "Central African Republic"),
    ("CG", "刚果（布）", "Republic of the Congo"),
    ("CH", "瑞士", "Switzerland"),
    ("CI", "科特迪瓦", "Cote d'Ivoire"),
    ("CL", "智利", "Chile"),
    ("CM", "喀麦隆", "Cameroon"),
    ("CN", "中国", "China"),
    ("CO", "哥伦比亚", "Colombia"),
    ("CR", "哥斯达黎加", "Costa Rica"),
    ("CU", "古巴", "Cuba"),
    ("CV", "佛得角", "Cabo Verde"),
    ("CY", "塞浦路斯", "Cyprus"),
    ("CZ", "捷克", "Czechia"),
    ("DE", "德国", "Germany"),
    ("DJ", "吉布提", "Djibouti"),
    ("DK", "丹麦", "Denmark"),
    ("DM", "多米尼克", "Dominica"),
    ("DO", "多米尼加", "Dominican Republic"),
    ("DZ", "阿尔及利亚", "Algeria"),
    ("EC", "厄瓜多尔", "Ecuador"),
    ("EE", "爱沙尼亚", "Estonia"),
    ("EG", "埃及", "Egypt"),
    ("ER", "厄立特里亚", "Eritrea"),
    ("ES", "西班牙", "Spain"),
    ("ET", "埃塞俄比亚", "Ethiopia"),
    ("EU", "欧盟", "European Union"),
    ("FI", "芬兰", "Finland"),
    ("FJ", "斐济", "Fiji"),
    ("FM", "密克罗尼西亚", "Micronesia"),
    ("FR", "法国", "France"),
    ("GA", "加蓬", "Gabon"),
    ("GB", "英国", "United Kingdom"),
    ("GD", "格林纳达", "Grenada"),
    ("GE", "格鲁吉亚", "Georgia"),
    ("GH", "加纳", "Ghana"),
    ("GM", "冈比亚", "Gambia"),
    ("GN", "几内亚", "Guinea"),
    ("GQ", "赤道几内亚", "Equatorial Guinea"),
    ("GR", "希腊", "Greece"),
    ("GT", "危地马拉", "Guatemala"),
    ("GW", "几内亚比绍", "Guinea-Bissau"),
    ("GY", "圭亚那", "Guyana"),
    ("HK", "香港", "Hong Kong"),
    ("HN", "洪都拉斯", "Honduras"),
    ("HR", "克罗地亚", "Croatia"),
    ("HT", "海地", "Haiti"),
    ("HU", "匈牙利", "Hungary"),
    ("ID", "印度尼西亚", "Indonesia"),
    ("IE", "爱尔兰", "Ireland"),
    ("IL", "以色列", "Israel"),
    ("IN", "印度", "India"),
    ("IQ", "伊拉克", "Iraq"),
    ("IR", "伊朗", "Iran"),
    ("IS", "冰岛", "Iceland"),
    ("IT", "意大利", "Italy"),
    ("JM", "牙买加", "Jamaica"),
    ("JO", "约旦", "Jordan"),
    ("JP", "日本", "Japan"),
    ("KE", "肯尼亚", "Kenya"),
    ("KG", "吉尔吉斯斯坦", "Kyrgyzstan"),
    ("KH", "柬埔寨", "Cambodia"),
    ("KI", "基里巴斯", "Kiribati"),
    ("KM", "科摩罗", "Comoros"),
    ("KN", "圣基茨和尼维斯", "Saint Kitts and Nevis"),
    ("KP", "朝鲜", "North Korea"),
    ("KR", "韩国", "South Korea"),
    ("KW", "科威特", "Kuwait"),
    ("KZ", "哈萨克斯坦", "Kazakhstan"),
    ("LA", "老挝", "Lao PDR"),
    ("LB", "黎巴嫩", "Lebanon"),
    ("LC", "圣卢西亚", "Saint Lucia"),
    ("LI", "列支敦士登", "Liechtenstein"),
    ("LK", "斯里兰卡", "Sri Lanka"),
    ("LR", "利比里亚", "Liberia"),
    ("LS", "莱索托", "Lesotho"),
    ("LT", "立陶宛", "Lithuania"),
    ("LU", "卢森堡", "Luxembourg"),
    ("LV", "拉脱维亚", "Latvia"),
    ("LY", "利比亚", "Libya"),
    ("MA", "摩洛哥", "Morocco"),
    ("MC", "摩纳哥", "Monaco"),
    ("MD", "摩尔多瓦", "Moldova"),
    ("ME", "黑山", "Montenegro"),
    ("MG", "马达加斯加", "Madagascar"),
    ("MH", "马绍尔群岛", "Marshall Islands"),
    ("MK", "北马其顿", "North Macedonia"),
    ("ML", "马里", "Mali"),
    ("MM", "缅甸", "Myanmar"),
    ("MN", "蒙古", "Mongolia"),
    ("MR", "毛里塔尼亚", "Mauritania"),
    ("MT", "马耳他", "Malta"),
    ("MU", "毛里求斯", "Mauritius"),
    ("MV", "马尔代夫", "Maldives"),
    ("MW", "马拉维", "Malawi"),
    ("MX", "墨西哥", "Mexico"),
    ("MY", "马来西亚", "Malaysia"),
    ("MZ", "莫桑比克", "Mozambique"),
    ("NA", "纳米比亚", "Namibia"),
    ("NE", "尼日尔", "Niger"),
    ("NG", "尼日利亚", "Nigeria"),
    ("NI", "尼加拉瓜", "Nicaragua"),
    ("NL", "荷兰", "Netherlands"),
    ("NO", "挪威", "Norway"),
    ("NP", "尼泊尔", "Nepal"),
    ("NR", "瑙鲁", "Nauru"),
    ("NZ", "新西兰", "New Zealand"),
    ("OM", "阿曼", "Oman"),
    ("PA", "巴拿马", "Panama"),
    ("PE", "秘鲁", "Peru"),
    ("PG", "巴布亚新几内亚", "Papua New Guinea"),
    ("PH", "菲律宾", "Philippines"),
    ("PK", "巴基斯坦", "Pakistan"),
    ("PL", "波兰", "Poland"),
    ("PS", "巴勒斯坦", "Palestine"),
    ("PT", "葡萄牙", "Portugal"),
    ("PW", "帕劳", "Palau"),
    ("PY", "巴拉圭", "Paraguay"),
    ("QA", "卡塔尔", "Qatar"),
    ("RO", "罗马尼亚", "Romania"),
    ("RS", "塞尔维亚", "Serbia"),
    ("RU", "俄罗斯", "Russia"),
    ("RW", "卢旺达", "Rwanda"),
    ("SA", "沙特阿拉伯", "Saudi Arabia"),
    ("SB", "所罗门群岛", "Solomon Islands"),
    ("SC", "塞舌尔", "Seychelles"),
    ("SD", "苏丹", "Sudan"),
    ("SE", "瑞典", "Sweden"),
    ("SG", "新加坡", "Singapore"),
    ("SI", "斯洛文尼亚", "Slovenia"),
    ("SK", "斯洛伐克", "Slovakia"),
    ("SL", "塞拉利昂", "Sierra Leone"),
    ("SM", "圣马力诺", "San Marino"),
    ("SN", "塞内加尔", "Senegal"),
    ("SO", "索马里", "Somalia"),
    ("SR", "苏里南", "Suriname"),
    ("SS", "南苏丹", "South Sudan"),
    ("ST", "圣多美和普林西比", "Sao Tome and Principe"),
    ("SV", "萨尔瓦多", "El Salvador"),
    ("SY", "叙利亚", "Syria"),
    ("SZ", "斯威士兰", "Eswatini"),
    ("TD", "乍得", "Chad"),
    ("TG", "多哥", "Togo"),
    ("TH", "泰国", "Thailand"),
    ("TJ", "塔吉克斯坦", "Tajikistan"),
    ("TL", "东帝汶", "Timor-Leste"),
    ("TM", "土库曼斯坦", "Turkmenistan"),
    ("TN", "突尼斯", "Tunisia"),
    ("TO", "汤加", "Tonga"),
    ("TR", "土耳其", "Turkey"),
    ("TT", "特立尼达和多巴哥", "Trinidad and Tobago"),
    ("TV", "图瓦卢", "Tuvalu"),
    ("TW", "中国台湾", "Taiwan, China"),
    ("TZ", "坦桑尼亚", "Tanzania"),
    ("UA", "乌克兰", "Ukraine"),
    ("UG", "乌干达", "Uganda"),
    ("US", "美国", "United States"),
    ("UY", "乌拉圭", "Uruguay"),
    ("UZ", "乌兹别克斯坦", "Uzbekistan"),
    ("VA", "梵蒂冈", "Holy See"),
    ("VC", "圣文森特和格林纳丁斯", "Saint Vincent and the Grenadines"),
    ("VE", "委内瑞拉", "Venezuela"),
    ("VN", "越南", "Vietnam"),
    ("VU", "瓦努阿图", "Vanuatu"),
    ("WS", "萨摩亚", "Samoa"),
    ("XK", "科索沃", "Kosovo"),
    ("YE", "也门", "Yemen"),
    ("ZA", "南非", "South Africa"),
    ("ZM", "赞比亚", "Zambia"),
    ("ZW", "津巴布韦", "Zimbabwe"),
]


def region_for_code(code: str) -> str:
    if code in AFRICA:
        return "非洲"
    if code in AMERICAS:
        return "美洲"
    if code in EUROPE:
        return "欧洲"
    if code in MIDDLE_EAST:
        return "中东"
    if code in CENTRAL_ASIA:
        return "中亚"
    if code in CAUCASUS:
        return "高加索"
    if code in SOUTH_ASIA:
        return "南亚"
    if code in EAST_ASIA:
        return "东亚"
    if code in SOUTHEAST_ASIA:
        return "东南亚"
    if code in OCEANIA:
        return "大洋洲"
    raise ValueError(f"country code has no region mapping: {code}")


def build_country_catalog() -> list[CountryCatalogItem]:
    rows: list[CountryCatalogItem] = []
    for code, name_zh, name_en in COUNTRY_ROWS:
        jurisdiction_type = "regional_bloc" if code == "EU" else "special_region" if code in {"TW", "HK", "MO"} else "country"
        rows.append(
            {
                "code": code,
                "name_zh": name_zh,
                "name_en": name_en,
                "region": region_for_code(code),
                "priority": PRIORITY_BY_CODE.get(code, "P3"),
                "jurisdiction_type": jurisdiction_type,
            }
        )
    return rows


FULL_COUNTRY_CATALOG = build_country_catalog()
